
const strings = {
    registerRecycling: "Registrar Reciclaje",
    statistics: "Estadística",
    settings: "Configuración",
    about: "Acerca de",
    appName: "RECY-DATA", // Si necesitas un nombre para la aplicación
    weightLabel: 'Peso registrado (kg)',
    peopleLabel: 'Personas en la fuente',
    dateLabel: 'Fecha de almacenamiento inicial',
    placeholderWeight: 'Peso',
    placeholderPeople: 'Número de personas',
    assignDate: 'Asignar fecha',
    photoLabel: 'Foto de peso',
    noRegisteredItemsMessage: 'No tiene elementos registrados',
    login: 'Iniciar sesión',
    cleanDryWaste: 'Residuos limpios y secos como: plástico, vidrio, metales, papel y cartón.',
    contaminatedWaste: 'Papel higiénico, servilletas, papeles y cartones contaminados con comida; papeles metalizados, entre otros; residuos COVID-19 como tapabocas, guantes, entre otros.',
    foodWaste: 'Restos de comida, residuos de corte de césped y poda de jardín, etc.',
    labelCleanDryWaste: 'Residuos limpios y secos',
    labelContaminatedWaste: 'Residuos contaminados',
    labelFoodWaste: 'Residuos organicos',
    recover: 'Recuperar',
    password: 'Contraseña',
    login: 'Iniciar sesión',
    registerRecycling: 'Registrar Reciclaje',
    type: 'Tipo',
    registered: 'Registrarse',
    add: 'Agregar',
    sendRecoveryCode: 'Enviar código de recuperación',
    forgotPassword: '¿Olvidó su contraseña?',
    subType: 'Sub Tipo',
    institutionalInfo: 'Info Institucional',
    name: 'Nombre',
    grade: 'Grado',
    schoolGrade: 'Curso',
    rememberUser: 'Recordar usuario',
    list: 'Lista',
    mainMenu: 'Menu principal',
    recyclingRecord: 'Registro de reciclaje',
    recyclingRecordList: 'Lista de Registros de Reciclaje',
    AboutUs: 'Acerca de nosotros',
    register: 'Registro',
    camera: 'Cámara',
    flipCamera: 'Cabiar cámara',
    camera_permission_request: 'Necesitamos tu permiso para mostrar la cámara',
    weight: "Peso",
    number_of_people: "Número de personas",
    assign_date: "Asignar fecha",
    date: "Fecha",
    noRecords: 'No hay registros disponibles',
    saved: "Guardado con éxito",
    PhotoPreview: "Visualizar foto",
    cancel: "Cancelar",
    confirmLogoutTitle: "Confirmar cierre de sesión",
    confirmLogoutMessage: "¿Estás seguro de que quieres cerrar sesión?",
    cancelLogout: "Cierre de sesión cancelado",
    confirm: "Confirmar",
    LoggingOut: "Cerrando sesión"


    

    // Agrega más cadenas según sea necesario
  };
  
  export default strings;